environment        = "production"
aws_region         = "eu-west-1"
vpc_cidr           = "10.0.0.0/16"
kubernetes_version = "1.29"
rds_instance_class = "db.r6g.large"
redis_node_type    = "cache.r6g.large"
