export enum ErrorCode {
  // Authentication errors
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_ACCOUNT_DISABLED = 'AUTH_ACCOUNT_DISABLED',
  AUTH_ACCOUNT_LOCKED = 'AUTH_ACCOUNT_LOCKED',
  AUTH_MFA_REQUIRED = 'AUTH_MFA_REQUIRED',
  AUTH_MFA_INVALID_CODE = 'AUTH_MFA_INVALID_CODE',
  AUTH_MFA_ALREADY_ENABLED = 'AUTH_MFA_ALREADY_ENABLED',
  AUTH_MFA_NOT_ENABLED = 'AUTH_MFA_NOT_ENABLED',
  AUTH_MFA_TOKEN_INVALID = 'AUTH_MFA_TOKEN_INVALID',
  AUTH_DEVICE_INVALID_TOKEN = 'AUTH_DEVICE_INVALID_TOKEN',
  AUTH_DEVICE_NOT_FOUND = 'AUTH_DEVICE_NOT_FOUND',
  AUTH_TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',
  AUTH_LOGIN_ANOMALY = 'AUTH_LOGIN_ANOMALY',

  // User errors
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_INVALID_ROLE = 'USER_INVALID_ROLE',
  USER_CANNOT_DELETE_SELF = 'USER_CANNOT_DELETE_SELF',

  // Partner errors
  PARTNER_NOT_FOUND = 'PARTNER_NOT_FOUND',
  PARTNER_SLUG_TAKEN = 'PARTNER_SLUG_TAKEN',
  PARTNER_HAS_ACTIVE_VENUES = 'PARTNER_HAS_ACTIVE_VENUES',

  // Venue errors
  VENUE_NOT_FOUND = 'VENUE_NOT_FOUND',
  VENUE_HAS_ACTIVE_DEVICES = 'VENUE_HAS_ACTIVE_DEVICES',

  // Advertiser errors
  ADVERTISER_NOT_FOUND = 'ADVERTISER_NOT_FOUND',
  ADVERTISER_SLUG_TAKEN = 'ADVERTISER_SLUG_TAKEN',
  ADVERTISER_HAS_ACTIVE_CAMPAIGNS = 'ADVERTISER_HAS_ACTIVE_CAMPAIGNS',

  // Campaign errors
  CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_INVALID_STATUS_TRANSITION = 'CAMPAIGN_INVALID_STATUS_TRANSITION',
  CAMPAIGN_INVALID_DATE_RANGE = 'CAMPAIGN_INVALID_DATE_RANGE',
  CAMPAIGN_BUDGET_EXCEEDED = 'CAMPAIGN_BUDGET_EXCEEDED',
  CAMPAIGN_NO_CREATIVES = 'CAMPAIGN_NO_CREATIVES',
  CAMPAIGN_ALREADY_ACTIVE = 'CAMPAIGN_ALREADY_ACTIVE',

  // Creative errors
  CREATIVE_NOT_FOUND = 'CREATIVE_NOT_FOUND',
  CREATIVE_FILE_TOO_LARGE = 'CREATIVE_FILE_TOO_LARGE',
  CREATIVE_INVALID_FORMAT = 'CREATIVE_INVALID_FORMAT',
  CREATIVE_UPLOAD_FAILED = 'CREATIVE_UPLOAD_FAILED',
  CREATIVE_PROCESSING_FAILED = 'CREATIVE_PROCESSING_FAILED',

  // Device errors
  DEVICE_NOT_FOUND = 'DEVICE_NOT_FOUND',
  DEVICE_SERIAL_ALREADY_EXISTS = 'DEVICE_SERIAL_ALREADY_EXISTS',
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  DEVICE_COMMAND_FAILED = 'DEVICE_COMMAND_FAILED',

  // Schedule errors
  SCHEDULE_NOT_FOUND = 'SCHEDULE_NOT_FOUND',
  SCHEDULE_CONFLICT = 'SCHEDULE_CONFLICT',
  SCHEDULE_INVALID_TIME_RANGE = 'SCHEDULE_INVALID_TIME_RANGE',

  // Invoice errors
  INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_PAID = 'INVOICE_ALREADY_PAID',
  INVOICE_PAYMENT_FAILED = 'INVOICE_PAYMENT_FAILED',

  // General errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
